//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class USER
    {
        public int ID { get; set; }

        [Required(ErrorMessage ="Trường này không được để trống")]
        public string USER1 { get; set; }

        [Required(ErrorMessage = "Trường này không được để trống")]
        [DisplayFormat(DataFormatString ="************")]  
        public string PASS { get; set; }
    }
}
